### PR TITLE
Switch from clipboard-ext to copypasta-ext

### PR DESCRIPTION
**Pull request by timvisee**
The `clipboard` crate backing `clipboard-ext` is not maintained anymore. I recommend to switch to `copypasta-ext`, which uses `copypasta` as backend. This is a fork of the original `clipboard` crate and is still maintained.

I'm maintaining both `clipboard-ext` and `copypasta-ext`.

In addition to this change, I updated all dependencies to their latest version.

### CODE REVIEW

**Review by AlexChaplinBraz — APPROVED** [review]
Cool! Didn't know it wasn't maintained any more, though it still worked fine. But I guess this way it gets Wayland support for free? Thanks a lot!

One question I have is whether I need to publish an update to crates.io as 1.0.1 when it's this type of change. I'm kinda new to this.

**Comment by timvisee** [comment]
Yeah, it still works for now, which is why I didn't yank this _old_ crate. But you never know how this works out in the future.

> One question I have is whether I need to publish an update to crates.io as 1.0.1 when it's this type of change. I'm kinda new to this.

Yes, releasing as `1.0.1` is fine, because it doesn't have any breaking changes (and you aren't exposing a library).

See these pages for more info on this:
- https://semver.org/
- https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field

**Comment by AlexChaplinBraz** [comment]
And one more question, I rebased from GitHub, but there's no "verified" mark any more even though we both have GPG signing set up. I just read that GitHub's rebase is somehow different from doing `git rebase`, so is there a proper way to merge pull requests and keep the signed commits? I'm sort of new to pull requests as well. I did one before, but I just stumbled through it and it was a while ago. Maybe I can still reverse it and redo it.

EDIT: Alright, I've looked into it and it seems that it's not possible for quite obvious reasons (not having access to the pull author's private GPG key) but I though it would be simpler, like pulling those exact commits into master. Well, it doesn't particularly matter. I could've fetched it and signed it locally, but... Meh.

**Comment by timvisee** [comment]
Yes, this happens because GitHub then (re)writes commits, and it doesn't have your private key.

You can do the merge/rebase locally which will sign it, then push and GitHub will automatically recognize the PR is merged. Next to the big green _Merge_ button it shows a _Use command line_ link (or something similar) which explains what commands to run to achieve this.

**Pull request merged**
